version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4-node
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: cimg/ruby:2.7.4-node
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:2.7.4-node
      - environment:
          POSTGRES_DB: news_app_fe_test
          POSTGRES_USER: news_app_fe
          POSTGRES_PASSWORD: ''
        image: cimg/postgres:14.1
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      PGHOST: 127.0.0.1
      PGUSER: news_app_fe
      PGPASSWORD: ''
      RAILSENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: |
              bundle exec rails db:create RAILS_ENV=test
              bundle exec rails db:migrate RAILS_ENV=test
      - ruby/rspec-test:
          label: RSpec tests
          include: spec/**/*_spec.rb

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build 